test-build-images:
    stage: test
    script:
       # - apt-get update -y
        - docker-compose -f code/darknet/build/docker-compose.yml build --no-cache
        # - docker-compose -f code/tf-obj-api/build/docker-compose.yml build --no-cache
        - docker-compose -f code/tf2/build/docker-compose.yml build --no-cache
        
        - docker-compose -f code/darknet/build/docker-compose.yml push
        # - docker-compose -f code/tf-obj-api/build/docker-compose.yml push
        - docker-compose -f code/tf2/build/docker-compose.yml push
    # only:
    #    - master
